name: Gsutil CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x, 3.11.x, 3.12.x, 3.13.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      env:
        PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"
    - name: Install dependencies
      run: |
        set -x
        git submodule update --init --recursive
    - name: Test
      run: |
        set -x
        python gsutil version -l
        python gsutil test -u
